openzipkin-contrib/zipkin-go-opentracing

bench_test.go
collector-scribe_test.go
concurrency_test.go
context.go
propagation.go
propagation_ot.go
propagation_test.go
raw.go
recorder.go
recorder_test.go
span.go
span_test.go
tracer.go
zipkin-recorder.go

Added BaggageItem method to adhere to OpenTracing Interface update and mirrored the immutable SpanContexts logic as shown in the basictracer-go implementation

Implement immutable SpanContexts

---

_thrift/compile.sh
_thrift/gen-go/scribe/constants.go
_thrift/gen-go/scribe/scribe-remote/scribe-remote.go
_thrift/gen-go/scribe/scribe.go
_thrift/gen-go/scribe/ttypes.go
_thrift/gen-go/zipkincore/constants.go
_thrift/gen-go/zipkincore/ttypes.go
collector-kafka.go
collector-kafka_test.go
collector-scribe.go
collector-scribe_test.go

Official apache thrift git repository is often slow and sometimes seems down. This introduces dependency import problems for Go projects using `zipkin-go-opentracing`. 
Moving to the github mirror might remedy these issues like #20

moved thrift import dependencies from apache to github repository

---

tracer.go

This adds a method of setting newSpanEventListener, allowing us to
use NetTraceIntegrator.
The events/ directory (from basictracer-go), should probably me removed

Add NewSpanEventListener as an option.

---

event.go
events/event_nettrace.go
json.go
raw.go
span.go
span_test.go
testutil_test.go
zipkin-recorder.go

This PR finishes the work started in PR #25 and handles OpenTracing key-value logging in the same way as Jaeger. If only a single key-value log Field exists with key "event", the payload of the log Field will be used instead of a JSON object with log Fields.

Handle OpenTracing key-value logging, finished work in PR #25

---

tracer.go
zipkin-endpoint.go

Very high port numbers where not serialized into the Zipkin struct properly due to using int16 instead of uint16 and therefore failing to create the Zipkin endpoint structs.
Also fixed Zipkin V1 style same span for Client and Server node. This has been broken since some OT update to the ext package.

bugfixes to endpoint serialization and RPC same span handling

---

propagation_ot.go

This bridges support for 128bit trace ids by not failing on their
receipt. Basically, this throws out any hex characters to the left
of the 16 needed for the 64bit trace id.
see: https://github.com/openzipkin/b3-propagation/issues/6

Tolerate 128bit trace ids by throwing out high bits

---

context.go
tracer.go
zipkin-recorder.go

In the past the tracer would always record and report timestamp and duration for each span.
To adhere to best practices the tracer will not report timestamp and duration in `clientServerSameSpan` mode for server side spans that have an existing client side counterpart.
See: https://github.com/openzipkin/openzipkin.github.io/issues/49

adhere to timestamp best practices for RPC mode server side spans

---

collector-http.go
collector-scribe.go

Look at this method,  the loop goroutine posts empty span list every interval, which is inefficient.
```go
func (c *HTTPCollector) loop() {
tickc := time.Tick(c.batchInterval / 10)
for {
select {
case span := <-c.spanc:
c.batch = append(c.batch, span)
if len(c.batch) >= c.batchSize {
go c.sendNow()
}
case <-tickc:
if time.Now().After(c.nextSend) {
go c.sendNow()
}
case <-c.sendc:
c.nextSend = time.Now().Add(c.batchInterval)
if err := c.send(c.batch); err != nil {
_ = c.logger.Log("err", err.Error())
}
c.batch = c.batch[:0]
case <-c.quit:
return
}
}
}
```
when ticker timeout, this goroutine will send c.batch to zipkin even though c.batch is empty. It should check the batch's size? like below:
```go
case <-tickc:
if time.Now().After(c.nextSend) && len(c.batch) > 0 {
go c.sendNow()
}
```

Check http batch size before sending

---

collector-http.go
collector-http_test.go
collector-scribe.go
collector-scribe_test.go
examples/cli_with_2_services/cli/main.go

Update the Close() logic of the HTTP and Scribe Collectors to drain any
pending spans before returning. This provides a mechanism to prevent
loss of buffered trace data when shutting down.
This is of particular use for short lived processes such as cli clients.

Drain collector buffer on Close

---

collector-http.go

Previously it was impossible to configure advanced options in the HTTPCollector,
like TLS. This patch allows users to pass any *http.Client configured the way they like.

new: added an HTTPOption to set a custom http.Client to use.

---

types/traceid.go
types/traceid_test.go

In working with several other opentracing libraries (sleuth in particular,) if a low enough TraceID.High value is created, sleuth with think it's a 64bit traceID.
This is also more consistent with how the TraceID.Low is generated and displayed.

Adding padding to 128 bit traceIDs

---

collector-http.go
collector-http_test.go

This allows one to adjust the request payload before the Collector sends the spans to Zipkin. 
Ideal to add items like Authorization headers and such.
This fixes #59.

Added HTTPRequestCallback HTTP Collector option

---

propagation_test.go
span_test.go
tracer.go

In hindsight it was a bad idea to default to single host spans as regular Zipkin V1 eco systems expect both client and server side of an RPC to be in the same span. 
Without them being in the same span, issues might occur wrt items like Zipkin's clock skew correction logic.
Also updated the propagation test to include a parent span for testing the X-B3-Parentspanid header.

Changed default for ClientServerSameSpan to true to respect Zipkin V1 better.

---

observer.go
span.go
tracer.go

Perf events can provide additional insights into the performance of a
span or a sequence of spans in a trace. This patch includes the use of
a library called
"perfevents" (https://github.com/opentracing-contrib/perfevents) which
can be simply imported and used. This library is an abstraction of the
platform side of counters and operations. Right now, only the generic
perf events are supported. With this patch, one should be able to find
out the cpu-cycles, instructions, cache-references, cache-misses,
branch-instructions, branch-misses and bus cycles for a span.
The required event(s) should be supplied in the form of a string(comma
separated list if there are multiple events to be monitored) to the
StartSpan call and then, the opentracing-go library and the
zipkin-go-opentracing library …

Monitoring platform events with zipkin-go and opentracing

---

collector-scribe.go
thrift/gen-go/scribe/scribe-remote/scribe-remote.go
thrift/gen-go/scribe/scribe.go

Interface / Implementation issue has been fixed in the latest Go lib allowing for symmetry in method signature in both Client and Server thus adhering again to the generated `Scribe` interface

update thrift generated code to lastest Go lib (including context)

---

circle.yml

current blank circle-ci logic caches dependencies. we want tests against all latest state of dependencies given we don't vendor in the library.

improve circle-ci build logic

---

examples/cli_with_2_services/svc2/implementation.go
zipkin-recorder.go

Binary annotations in non string format have the downside of not being usable as query item in the Zipkin UI. 
Zipkin V2 is dropping support for non string values so we're switching over to automatically converting non string values to string.

Treat all tag values as string

---

wire/wire.proto

They've changed the expected package option: golang/protobuf#139
In particular, this is needed if you include this in a project build with bazel.

Update go_package in wire.proto to reflect new spec.

---

thrift/gen-go/scribe/scribe-remote/scribe-remote.go
thrift/gen-go/scribe/scribe.go

There have been some changes to the Go thrift library that are incompatible with the existing generated thrift code. The code has been regenerated with the latest thrift compiler and latest Go thrift library

regenerated thrift code based on latest thrift compiler and go thrift lib

---

bench_test.go

Fixes #92.
Fix up a couple of the benchmarks that seemed to have
been copied and pasted without magnitude change in either:
* numEvents
* numTag
* numItems

tests/bench: fix Benchmark copy and paste magnitudes

---

propagation_ot.go
propagation_test.go
types/traceid.go

Lower numbers represented in HEX where not prefixed with 0's so not adhering to B3 standard which requires:
- traceid's 32 hex chars in case of 128bit / 16 hex chars in case of 64 bit
- spanid & parentspanid: 16 hex chars
closes #97

fixed B3 hex encoding issues with trace identifiers.

---

zipkin-recorder.go

No need to show span.kind in Zipkin's Span details. We have our core annotations.

remove span.kind from span details after having set zipkin core annotations

---

collector.go
collector_test.go

Currently, if no `Collect()` call returns an error in the `MultiCollector` implementation, `aggregateError` will return a `nil` `collectionError` that will not be correctly comparable to `nil` from the caller.
This PR should fix issue https://github.com/openzipkin-contrib/zipkin-go-opentracing/issues/115.

Make aggregateErrors return nil when no errors in multi collect

---

collector-http.go
collector-http_test.go

This PR fixes the go routine proliferation that happens when system is under load.
Under load this code has >90K active goroutines. See https://github.com/istio/issues/issues/100#issuecomment-339468537 for more details.
1. Simplify http-collector, no new go routines are launched.
2. Use a non-blocking write into a buffered channel.
3. As a consequence of #2, the latest spans are dropped under load,
not the oldest.

Fix go routine proliferation in http-collector

---

.travis.yml
propagation_ot.go
propagation_test.go

* Fail if a required field (TraceID or SpanID) is not set
* Support carriers that only specify TraceID and SpanID
Fixes #118

Fix bugs in textMapPropagator.Extract

---

collector-http.go
collector-scribe.go

When a Collector is closed while other goroutines are attempting to
record spans, it shouldn't deadlock.

Avoid deadlocking when Collector Closed concurrently with Collect call

---

examples/cli_with_2_services/cli/main.go
examples/cli_with_2_services/svc1/cmd/main.go
examples/cli_with_2_services/svc2/cmd/main.go
span.go
tracer.go
tracer_options.go

This PR adds support for native tracer options for tracer. Also it brings it back the observer feature to the tracer.
We managed to wrap most o the options and tried to keep the same function names, removed some and added some others however notice we still depend on zipkin package for the `Wrap`.
Questions to be answered:
1. Should we still include the options that are not supported anymore?
2. Should we keep the recorder as it is?
Ping @basvanbeek @stakhiv

feat: adds tracer native options.

---

sample.go
tracer_options.go

While migrating one service from the old to the new service I found that the `Sampler` type was missing so I am adding here.
Ping @stakhiv @basvanbeek

chore(zipkin): adds sampler type to ease migration.

---

tracer.go

Whoopsie... we changed the SpanContext signature and it wasn't picked up anymore from the internal StartSpan function.
We'll need to add a test case for this so we won't regress in the future.

fixes broken parent context import due to signature change of SpanContext

---

tracer.go

span.kind OT tag sometimes is sent as string but if using ext package it will be ext.SpanKindEnum.
This allows for both types to be handled properly.

Improve handling of span.kind OT tag

---

tracer.go
tracer_test.go

This PR changes the parsing of span kind and defaults to a tag when the kind can't be matched with zipkin kind. Ping @basvanbeek

tests: adds span kind test.

---

go.mod
go.sum
propagation.go

This adds TextMapReader and TextMapWriter compatibility once the following PR https://github.com/openzipkin/zipkin-go/pull/145  is merged and available in a release of Zipkin Go.

add TextMapReader and TextMapWriter compatibility

---

propagation.go
propagation_test.go

Lot's of uncaught errors on the propagation tests allowed returning an error after a successful `Inject`.
Other packages relying on this code will, or should at least, check for errors and they will always fail in this situation.
Related to #151

fix invalid carrier thrown when falling back to text map carrier

---

propagation.go
propagation_test.go

Currently, when trying to extract the context from a carrier that implements `opentracing.TextMap`, the extraction fails if the carrier contains headers in the non-standard way, e.g. http headers like `X-B3-Traceid`. This does not happen if one use the `opentracing.HTTPHeadersCarrier` but if one uses a custom carrier like [traefik does](https://github.com/containous/traefik/blob/master/pkg/tracing/carrier.go#L7).
Whether we `traefik` should use its own carrier or use the `OT` one, in our side it makes sense that we standarize `http headers` because then we aim to retrieve them using lower cases: see https://github.com/openzipkin/zipkin-go/blob/master/propagation/b3/shared.go
Related to https://github.com/containous/traefik/issues/5511
Ping @basvanbeek @trajano

fix(propagation): fixes propagation for opentracing.TextMap.
